"""
Known legitimate brand targets used as reference for similarity comparison.
"""

DEFAULT_TARGETS = [
    {"name": "Google", "domain": "google.com", "category": "Technology",
     "login_url": "https://accounts.google.com", "keywords": ["google", "gmail", "gsuite", "goog"]},
    {"name": "Microsoft", "domain": "microsoft.com", "category": "Technology",
     "login_url": "https://login.microsoftonline.com", "keywords": ["microsoft", "msft", "outlook", "office365", "azure"]},
    {"name": "Apple", "domain": "apple.com", "category": "Technology",
     "login_url": "https://appleid.apple.com", "keywords": ["apple", "icloud", "itunes", "applestore"]},
    {"name": "PayPal", "domain": "paypal.com", "category": "Finance",
     "login_url": "https://www.paypal.com/signin", "keywords": ["paypal", "paypall", "pay-pal"]},
    {"name": "Amazon", "domain": "amazon.com", "category": "E-Commerce",
     "login_url": "https://www.amazon.com/ap/signin", "keywords": ["amazon", "amaz0n", "amazonaws"]},
    {"name": "Facebook", "domain": "facebook.com", "category": "Social Media",
     "login_url": "https://www.facebook.com/login", "keywords": ["facebook", "fb", "faceb00k", "meta"]},
    {"name": "Netflix", "domain": "netflix.com", "category": "Entertainment",
     "login_url": "https://www.netflix.com/login", "keywords": ["netflix", "netfl1x", "neftlix"]},
    {"name": "Chase Bank", "domain": "chase.com", "category": "Banking",
     "login_url": "https://secure.chase.com", "keywords": ["chase", "jpmorgan", "chaseonline"]},
    {"name": "Bank of America", "domain": "bankofamerica.com", "category": "Banking",
     "login_url": "https://www.bankofamerica.com/login", "keywords": ["bankofamerica", "bofa", "bank0famerica"]},
    {"name": "Wells Fargo", "domain": "wellsfargo.com", "category": "Banking",
     "login_url": "https://www.wellsfargo.com", "keywords": ["wellsfargo", "wf", "wells-fargo"]},
    {"name": "Twitter/X", "domain": "twitter.com", "category": "Social Media",
     "login_url": "https://twitter.com/login", "keywords": ["twitter", "twit", "x.com", "twitterr"]},
    {"name": "LinkedIn", "domain": "linkedin.com", "category": "Professional Network",
     "login_url": "https://www.linkedin.com/login", "keywords": ["linkedin", "linked-in", "linkedln"]},
    {"name": "Instagram", "domain": "instagram.com", "category": "Social Media",
     "login_url": "https://www.instagram.com/accounts/login", "keywords": ["instagram", "insta", "1nstagram"]},
    {"name": "Dropbox", "domain": "dropbox.com", "category": "Cloud Storage",
     "login_url": "https://www.dropbox.com/login", "keywords": ["dropbox", "dr0pbox", "dropb0x"]},
    {"name": "Coinbase", "domain": "coinbase.com", "category": "Crypto",
     "login_url": "https://www.coinbase.com/signin", "keywords": ["coinbase", "c0inbase", "coinbas3"]},
    {"name": "Binance", "domain": "binance.com", "category": "Crypto",
     "login_url": "https://www.binance.com/login", "keywords": ["binance", "b1nance", "binance-us"]},
    {"name": "Steam", "domain": "steampowered.com", "category": "Gaming",
     "login_url": "https://store.steampowered.com/login", "keywords": ["steam", "steampowered", "steamcommunity"]},
    {"name": "DHL", "domain": "dhl.com", "category": "Logistics",
     "login_url": "https://www.dhl.com/login", "keywords": ["dhl", "dh1", "dhl-express"]},
    {"name": "FedEx", "domain": "fedex.com", "category": "Logistics",
     "login_url": "https://www.fedex.com/login", "keywords": ["fedex", "fed-ex", "fedeks"]},
    {"name": "UPS", "domain": "ups.com", "category": "Logistics",
     "login_url": "https://www.ups.com/login", "keywords": ["ups", "unitedparcel", "ups-tracking"]},
]
